### ISSUE TITLE
Set Usergroup rights for deleting galeries

### ISSUE THREAD

**Issue by fabcocco** [markocupic/gallery-creator-bundle#12]
There isn't a checkbox to control the right of an editor to allow him to delete galleries or edit settings. 

Every field of the tl_.... are set.

![image](https://user-images.githubusercontent.com/24480931/63863334-58a1c500-c9ae-11e9-98f3-18e27322851f.png)
![Anmerkung 2019-08-28 160852](https://user-images.githubusercontent.com/24480931/63863351-5dff0f80-c9ae-11e9-82bf-ba523a25dc3e.png)

**Comment by markocupic** [comment]
introduced in https://github.com/markocupic/gallery-creator-bundle/tree/2.0.0-RC2/src/Widget/Backend
