### ISSUE TITLE
Problem mit Routing in Contao 4.8 

### ISSUE THREAD

**Issue by mlwebworker** [markocupic/gallery-creator-bundle#13]
Beim Update auf Contao 4.8 werden zum einen die Bilder in der Lightbox nicht mehr gefunden. Zum anderen funktioniert die Weiterleitung von der Liste der Galerien auf die Einzelgalerien nicht mehr. Es scheint sich um ein Problem beim Routing zu handeln.
In 4.7 sind die Pfade nach dem Muster https://meinedomain.de/index/galeriename.html aufgebaut. In Contao 4.8 wird die URL https://meinedomain.de/galeriename.html angesprochen und nicht gefunden.
Für den Test habe ich alle angepassten Templates eliminiert und testweise auch eine neue Galerie aufgebaut.

**Comment by markocupic** [comment]
Oh... Bin im Moment gerade sehr busy. 
Kann dir nicht versprechen, bis wann ich das gefixt habe.
Ich danke dir für dein Verständnis 
Lg Marko

**Comment by mlwebworker** [comment]
Kein Thema. Hat Zeit. Ist meine private Seite. Die Live-Version läuft noch unter Contao 4.7
