### ISSUE TITLE
Contao 4.9.2 | Mehrere Detailansichten

### ISSUE THREAD

**Issue by satinez** [markocupic/gallery-creator-bundle#14]
Leider bekomme ich mehr als 1 Galerie nicht zum laufen sobald eine Galerie in der Detailansicht mit der Funktion Weiterleitung bei einzelnem Album aktiviert ist. Was mache ich falsch?
Fehlermeldungen habe ich keine in der error.log, es wird nicht mal das HTML für das 2te generiert.

Habe auch das gc_colorbox_,multipage Template ausprobiert, leider nichts.
<img width="874" alt="only1_gallery" src="https://user-images.githubusercontent.com/14118175/81352084-f749fe00-90c5-11ea-81c2-d8ee7b30f9ff.png">

Hat es damit zu tun das bei der Detailansicht eine **nur** eine ID des containers "galleryContainer" existieren darf?

Danke :)

**Comment by markocupic** [comment]
Wo kann man das live sehen?

Nur kurz... Eigentlich macht es ja keinen Sinn die Weiterleitung zu aktivieren, wenn du mehrere GC Inhaltselemente auf einer Seite platzierst. Das zweite Inhaltselement kann nie aktiv werden, weil das System die Inhaltselemente von oben nach unten abarbeitet und beim ersten Inhaltselement weiterleitet.

**Comment by satinez** [comment]
Danke für deine rasche Antwort. Leider kann ich den Link hier nicht publizieren.
Das Ziel ist auf einer Seite mehrere Detailansichten zu platzieren. Oder gibt es da die eine oder andere Möglichkeit?

![mehreregallerienimdetail](https://user-images.githubusercontent.com/14118175/81380384-1d45c180-910b-11ea-8bc8-1af9ea5d9f1c.png)
