### ISSUE TITLE
Keine Thumbnails im Gallery-Creator-Bundle in Contao 4.11

### ISSUE THREAD

**Issue by PeterWolf242** [markocupic/gallery-creator-bundle#15]
Ich habe von Contao 3.0 auf Contao 3.5 und dann auf 4.11 das Update gemacht. Hat auch soweit funktioniert bis auf den Gallery-Creator. Ich habe das Gallery-Creator-Bundle über das Install-Tool installiert aber im Backend übernimmt er weder das upload-Verzeichnis noch das er mir die Thumbnails anzeigt. Auf dem FTP-Server sind die Bilder physisch vorhanden. Ich habe sogar auf dem FTP-Server einen komplett neuen Ordner für die Bilder angelegt und via Filezilla die Fotos rüberkopiert aber er übernimmt gar nix davon. Auch das deinstallieren des Bundle-Paketes hat nix gebracht. Der Prod-Cache wurde neu geschrieben, Datenbanken sind aktuell und synchronisiert ist auch alles. Ich bin mittlerweile mit meinem Latein am Ende. Wäre echt super wenn jemand eine Idee hätte wo das Problem liegt.  Bei Bedarf wäre sicher auch eine Fernwartung möglich.

**Comment by markocupic** [comment]
Hallo Peter
Bitte nimm mit mir per Email Kontakt auf. 
m.cupic@gmx.ch 
LG marko
