### ISSUE TITLE
Contao 4.13-RC1: request.CRITICAL: Uncaught PHP Exception

### ISSUE THREAD

**Issue by Seefahrer** [markocupic/gallery-creator-bundle#16]
Trying to edit an article (content element) with a Gallery Creator element leads to fllwg error:

`
[request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\ClassNotFoundError: "Attempted to load class "Utf8" from namespace "Patchwork". Did you forget a "use" statement for another namespace?" at /www/htdocs/w00c556f/cmsc4ME/vendor/markocupic/gallery-creator-bundle/src/Resources/contao/elements/ContentGalleryCreator.php line 76 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\ClassNotFoundError(code: 0): Attempted to load class \"Utf8\" from namespace \"Patchwork\".\nDid you forget a \"use\" statement for another namespace? at /www/htdocs/w00c556f/cmsc4ME/vendor/markocupic/gallery-creator-bundle/src/Resources/contao/elements/ContentGalleryCreator.php:76)"} []
`

**Comment by markocupic** [comment]
Please try version [dev-2](https://github.com/markocupic/gallery-creator-bundle/tree/dev-2.0).

But be aware that in this version your old templates will no longer work.

**Comment by Seefahrer** [comment]
**Contao 4.12.5 and 4.13-RC1, package dev-dev-2.0 with formerly existing albums :**

Invoking „`Inhalte > Gallery Creator`“ in the backend results in fllwg error message:

>request.CRITICAL: Uncaught PHP Exception TypeError: "str_replace(): Argument #2 ($replace) must be of type array|string, int given" at /Users/georg/Websites/cmsc4ME/vendor/markocupic/gallery-creator-bundle/src/DataContainer/GalleryCreatorAlbums.php line 402 {"exception":"[object] (TypeError(code: 0): str_replace(): Argument #2 ($replace) must be of type array|string, int given at /Users/georg/Websites/cmsc4ME/vendor/markocupic/gallery-creator-bundle/src/DataContainer/GalleryCreatorAlbums.php:402)"} []

Invoking an album in the frontend results in the same error message as above:

**Only in 4.13-RC1 the frontend becomes totally unreachable** with fllwg error message related to symphony:

> equest.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "contao.monolog.logger.error"." at /Users/georg/Websites/cmsc4ME/vendor/symfony/dependency-injection/Container.php line 271 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"contao.monolog.logger.error\". at /Users/georg/Websites/cmsc4ME/vendor/symfony/dependency-injection/Container.php:271)"} []

In 4.12.5 there are no images displayed in the albums

**Comment by Seefahrer** [comment]
Hallo Marco,

habe entsprechend der Änderung in den contao core files https://github.com/contao/contao/commit/267ef46f5f71423da0c1dc942841c49a280765dc in der `dev-master` in `ContentGalleryCreator.php line 76 `mal geändert in:

`$objTemplate->wildcard = '### ' . $GLOBALS['TL_LANG']['CTE']['gallery_creator_ce'][0] . ' ###';`

und `use Patchwork\Utf8;` entfernt, da das ja abandoned ist. Damit läuft es auch in `Contao 4.13-RC1`

Im Installtool bleibt nach der DB-Aktualisierung noch folgendes requirement dauerhaft stehen:
`ALTER TABLE tl_gallery_creator_albums CHANGE alias alias VARCHAR(128) DEFAULT '' NOT NULL COLLATE 'utf8_bin‘`

Ist vielleicht auch nur eine Kleinigkeit ... ?

**Comment by Seefahrer** [comment]
**Contao 4.12.5 and 4.13-RC1, package dev-dev-2.0:**

The error concerning 

> request.CRITICAL: Uncaught PHP Exception TypeError: "str_replace(): Argument https://github.com/markocupic/gallery-creator-bundle/pull/2 ($replace) must be of type array|string, int given" at /Users/georg/Websites/cmsc4ME/vendor/markocupic/gallery-creator-bundle/src/DataContainer/GalleryCreatorAlbums.php line 402

can be fixed by replacing the mentioned line with the following:

`$label = str_replace('#count_pics#', strval($countImages), $label);`

The further reported error re `contao.monolog.logger.error` has been fixed in the contao core with `Contao 4.13-RC3`.

Nevertheless there are still no images shown in the galleries/albums ...

**Comment by markocupic** [comment]
@Seefahrer Please check if there are more errors.
