### ISSUE TITLE
Contao 4.13-RC3, Gallery Creator „dev-2.0“ - Attempted to call an undefined method

### ISSUE THREAD

**Issue by Seefahrer** [markocupic/gallery-creator-bundle#18]
If I try to upload images from an existing folder, the attempt so save the selected folder/images results in fllwg error:

> request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\UndefinedMethodError: "Attempted to call an undefined method named "getAbsolutePath" of class "Contao\Model\Collection"

**Comment by markocupic** [comment]
Fixed in https://github.com/markocupic/gallery-creator-bundle/commit/0805d9e0cc4d483c0cf7d3d6c389fd06c3dcb1c0
