### ISSUE TITLE
Gallery Creator „dev-2.0“ - No images in Frontend

### ISSUE THREAD

**Issue by Seefahrer** [markocupic/gallery-creator-bundle#19]
I created lots of galleries in the former GC 1.x (dev-master) before I upgraded to GC dev 2.0. Despite all images are listed in the Gallery Creator backend module and properly selected in the corresponding Gallery Creator content element, no images are shown in the frontend („0 images“ ... „0 Hits“). The problem occurs in both Contao 4.12.6 and 4.13-RC3.

As GC dev-2.0 is currently running on a local MAMP Pro 6.6.1 installation, I cannot provide any link.

**Comment by markocupic** [comment]
@Seefahrer 

I just did a test migration with two galleries from 1.2.11 to dev-dev-2.0 successfully (Contao 4.13-RC3),.

Do you use any Gallery Creator custom templates? 

Has the migration script been run properly?

Have you checked the element settings in the Contao backend?

Perhaps you should again try a migration.

**Comment by Seefahrer** [comment]
No custom templates in dev-2.0 are used. Element settings are all ok. But which migration script needs to be run?
The Installtool with database migration has for sure been run ...

But meanwhile I found out what is going wrong:
Because I have lots of galleries, I’ve organised my galleries in a hierarchy of main- and sub-galleries wherein the main-galleries are actually empty but whereas **all images** are stored in the sub-galleries.

Obviously GC does not load images from sub-galleries (just tested) but only from main-/first level galleries despite sub-galleries are selectable in the backend content element. And, as the main gallery ist empty, no images are being displayed.

For testing I moved a gallery to the first level and - voilà - it’s being displayed ...

**Comment by markocupic** [comment]
You have to run contao/install simply.

Do nothing now. I'll test the behaviour with child galleries this evening and I will let you know. ok?

**Comment by Seefahrer** [comment]
Marco,
schön wäre es auch wenn man wieder direkt von der Ansicht des Galeriebildes in die Detailansicht in der Glightbox kommen könnte.

**Comment by markocupic** [comment]
@Seefahrer Please try again ;-)

**Comment by Seefahrer** [comment]
Hi Marco,

now it’s so far working fine BUT, referring to my hierarchy example there is still an issue:
In the list view of the child galleries there is still a backlink to the actual empty parent gallery which leads to a blank page.
I’ve tried to {display: none} it via css but then also the backlink in the detail view is gone ...
Bottom line, this backlink shouldn’t be displayed at all.

And finally my ever lasting feature request ;-) ...
What do you think of a -may be- checkbox wherein a user can decide whether the detail view of galleries either will be displayed on the regular detail page or directly as slideshow in the lightbox?!

**Comment by Seefahrer** [comment]
Just as I have written above lines, the problem is back ... list view is empty :-(
I remember that I clicked once on the backlink in the listview just to confirm again that a backlink into the empty parent gallery is possible.
Afterwards I started to assign galleries to gc content elements in articles. After some assignments I just made a short test, but no galleries are being displayed. Script, page and Symfony cache cleared, GC removed and reinstalled, still no galleries.
Then I moved again some galleries to the parent (first) level - everything is fine.

Finally the basic problem seems to prevail ...

**Comment by markocupic** [comment]
Hm...
Could you post a screenshot of your ce-settings and another one of your gallery tree?

**Comment by Seefahrer** [comment]
Just to say ist: all settings are identical with my settings in the old GC which is still working perfect online:
see (https://www.luetten-dieks.eu/unsere-erlebnisse).

Screenshots of GC 2.0:
<img width="1791" alt="Bildschirmfoto 2022-02-14 um 10 52 31" src="https://user-images.githubusercontent.com/12233592/153842437-c6edda3c-c638-49e2-acf1-99f4b5dac9ec.png">
<img width="1791" alt="Bildschirmfoto 2022-02-14 um 10 55 27" src="https://user-images.githubusercontent.com/12233592/153842444-09284983-9c53-4c45-b286-0b15c5092816.png">
<img width="1791" alt="Bildschirmfoto 2022-02-14 um 10 56 07" src="https://user-images.githubusercontent.com/12233592/153842448-6d9e6cc2-3b1d-4c55-b3d8-378979a590ba.png">
<img width="1791" alt="Bildschirmfoto 2022-02-14 um 10 56 55" src="https://user-images.githubusercontent.com/12233592/153842454-71a70b0e-f4d3-45cf-9d09-aa39def7035e.png">

**Comment by Seefahrer** [comment]
Marco,

I just saw that also all image captions are gone upon migrating from 1.x to dev 2.0. 
‚Comment‘ --> Caption‘. Another issue to be made up?

**Comment by markocupic** [comment]
> Marco,
> 
> I just saw that also all image captions are gone upon migrating from 1.x to dev 2.0. ‚Comment‘ --> Caption‘. Another issue to be made up?

Yes, but this should be fixed since https://github.com/markocupic/gallery-creator-bundle/commit/e4bf1c90516cd938a8e54d137e321cf212d7666c

**Comment by markocupic** [comment]
> Just to say ist: all settings are identical with my settings in the old GC which is still working perfect online: see (https://www.luetten-dieks.eu/unsere-erlebnisse).
> 
> Screenshots of GC 2.0: <img alt="Bildschirmfoto 2022-02-14 um 10 52 31" width="1791" src="https://user-images.githubusercontent.com/12233592/153842437-c6edda3c-c638-49e2-acf1-99f4b5dac9ec.png"> <img alt="Bildschirmfoto 2022-02-14 um 10 55 27" width="1791" src="https://user-images.githubusercontent.com/12233592/153842444-09284983-9c53-4c45-b286-0b15c5092816.png"> <img alt="Bildschirmfoto 2022-02-14 um 10 56 07" width="1791" src="https://user-images.githubusercontent.com/12233592/153842448-6d9e6cc2-3b1d-4c55-b3d8-378979a590ba.png"> <img alt="Bildschirmfoto 2022-02-14 um 10 56 55" width="1791" src="https://user-images.githubusercontent.com/12233592/153842454-71a70b0e-f4d3-45cf-9d09-aa39def7035e.png">

Please try the latest build ;-)

**Comment by Seefahrer** [comment]
Just did another migration of the original online db, it is fixed. All captions are in the db :-)

**Comment by markocupic** [comment]
Ende gut alles gut. Wohne übrigens im Kanton Luzern. Ins Entlebuch sind es gerade mal 10 km. ;-)
Schöne Bilder hast du auf deiner Seite.

Lg Marko

**Comment by Seefahrer** [comment]
Danke, „Knipsen“ ist mein Hobby. Dafür braucht es ja eine perfekte Galerie :-)

**Comment by Seefahrer** [comment]
Eine Kleinigkeit noch: wenn ein Bild kein Caption hat wird ja der Dateiname in der Lightbox ausgegeben.
Vielleicht solltest Du darauf verzichten. Sieht nicht immer schön aus, vor allem bei etwas kryptischen Dateinamen :😉

ebenfalls LG Georg

**Comment by Seefahrer** [comment]
Marko,
es gibt immer noch einen Backlink zur leeren parent gallery („zurück“). Wenn ich darauf clicke, lande ich auf einer leeren Seite. Die Bilder im listview der child Galerien und in der Detailansicht werden aber ausgegeben. Der Link auf die oberste Ebene müßte weg, wenn die Anzahl der Bilder dort =0 ist.

LG in die Schweiz

**Comment by Seefahrer** [comment]
By the way ... wenn ich euch da so in den Wänden sehe, wird mir beim bloßen Zusehen schon schwindelig ...

**Comment by markocupic** [comment]
> Marko, es gibt immer noch einen Backlink zur leeren parent gallery („zurück“). Wenn ich darauf clicke, lande ich auf einer leeren Seite. Die Bilder im listview der child Galerien und in der Detailansicht werden aber ausgegeben. Der Link auf die oberste Ebene müßte weg, wenn die Anzahl der Bilder dort =0 ist.
> 
> LG in die Schweiz

Ich weiss nicht, ob das der richtige Weg ist. Was ist, wenn du zwei leere Parent Galerien auf der obersten Ebene hast?

- Ausflüge 2021
- Ausflüge 2022

Wenn der Backlink nicht angezeigt wird, und du befindest dich in einem Unteralbum von "Ausflüge 2021", wie schaffst du es dann zu "Ausflüge 2022" zu gelangen?

Besser wäre es den Backlink mit einem HTML Attribut zu versehen. Dadurch könntest du den Link via CSS ansprechen und unsichtbar machen.

``` 
<div class="gc-album-detail-back-link" data-href="galerie/2021.html">
<a href="galerie/2021.html" title="zurück">zurück</a>
</div>
```

**Comment by Seefahrer** [comment]
Wenn ich ".gc-album-detail-back-link {display: none}" setze, blende ich auch den Backlink in den Unteralben aus.
Könnte man dem obersten Backlink nicht die Klasse "`gc-album-list-back-link`“ geben? Die könnte man gezielt mit CSS ausblenden ...

**Comment by Seefahrer** [comment]
ok, ok 🙃 

`.ce_gallery_creator .gc-album-detail-view .gc-album-detail-inner .gc-album-detail-back-link {
	display: none;
}`

blendet den Link aus ... Asche auf mein Haupt.

**Comment by Seefahrer** [comment]
... leider aber auch in den Unteralben 🥺

**Comment by Seefahrer** [comment]
It’s now very close to perfect 😁

**Comment by markocupic** [comment]
```
<div class="gc-album-detail-view" data-album-level="1">
  <div class="gc-album-detail-inner">
    <div class="gc-album-detail-back-link"><a href="galerie/parent-empty.html" title="zurück">zurück</a></div>
 </div>
</div>
```

Mit dem Album Level Attribut kannst du das Problem lösen, denke ich. Musst aber erneut updaten.

```
/** CSS **/
.gc-album-detail-view[data-album-level="1"] .gc-album-detail-back-link{
  display: none;
}
```

**Comment by Seefahrer** [comment]
Moin Marko,
das Problem ist ganz einfach zu lösen: Einfach im content element das oberste leere Verzeichnis deselektieren, dann wird auch kein zurück-link angezeigt.
Das Verhalten ist jetzt auch konsistent: wird das leere Verzeichnis selektiert, wird nach Aufruf der Seite aus dem Menü auch die leere Seite mit dem Titel (link) der leeren Galerie angezeigt. Von da aus geht es in die Subgallery. Also alles richtig.

**Comment by Seefahrer** [comment]
Habe jetzt mal eben meine o.g. Online-Seite auf die neue Version umgestellt. Ein wenig flex-CSS, sieht schonmal ganz brauchbar aus ...
Fehlt nur noch der direkte link in die glightbox 😬.

**Aber erst einmal: vielen Dank für Deine tolle Arbeit, Deine Hilfe und Dein Engagement!**

**Comment by markocupic** [comment]
> Fehlt nur noch der direkte link in die glightbox 😬.
Hat für mich im Moment keine Priorität. Kannst mich aber per E-Mail anfragen, wenn du dieses feature sponsern möchtest.
