### ISSUE TITLE
Contao 4.13 no routing

### ISSUE THREAD

**Issue by pbd-kn** [markocupic/gallery-creator-bundle#21]
https://mitleben-ev.de/bildergalerien-2022/id-2022-essen-februar.html

Beim auruf des Galerie-Creator-Inhaltselemaents und der Auswahl eines Bildes erscheint der Fehler Seite nicht vorhanden (404)

NotFoundHttpException
in vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php (line 97)
in vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php -> convertToHttpException (line 68)
in vendor/symfony/event-dispatcher/Debug/WrappedListener.php -> __invoke (line 117)
in vendor/symfony/event-dispatcher/EventDispatcher.php -> __invoke (line 230)
in vendor/symfony/event-dispatcher/EventDispatcher.php -> callListeners (line 59)
in vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 154)
in vendor/symfony/http-kernel/HttpKernel.php -> dispatch (line 213)
in vendor/symfony/http-kernel/HttpKernel.php -> handleThrowable (line 85)
in vendor/symfony/http-kernel/Kernel.php -> handle (line 202)
Kernel->handle(object(Request)) in web/index.php (line 44)

    $loader = require __DIR__.'/../vendor/autoload.php';
    $request = Request::createFromGlobals();
    $kernel = ContaoKernel::fromRequest(dirname(__DIR__), $request);
    $response = $kernel->handle($request);
    $response->send();
    if ($kernel instanceof TerminableInterface) {
        $kernel->terminate($request, $response);
    }

**Comment by pbd-kn** [comment]
contao 4.13.4
Galleriecreator 1.2.11


GALLERY-CREATOR-INHALTSELEMENT
![grafik](https://user-images.githubusercontent.com/75879364/169507140-e72f4611-4f4b-4879-a7e8-fff17deed6b9.png)

Fehler 404
![grafik](https://user-images.githubusercontent.com/75879364/169507240-30e0bd54-93c4-4a83-b3cc-806d2af9f55a.png)

Der Fehler tritt bei allen Inhaltslementen auf, sobald ich ein eines Bild anzeigen will

**Comment by pbd-kn** [comment]
Nochmals,
Reproduzierbar
https://mitleben-ev.de/bildergalerien-2022.html
Klick auf eine Galerie z.B. 2022 April Wanderung

**Comment by janborg** [comment]
Hast du schon php8? Dafür ist die Erweiterung m.W. noch nicht eingerichtet. Mit php7.4 funktioniert bei mir noch alles einwandfrei. 
Für php8 arbeitet Marco schon an einer Version 2 für den es aktuell ab nur einen RC gibt. Dieser funktioniert bei mir aber im Test schon sehr gut unter php8.1

Gruß Jan

PS: am besten immer debug:mode on und stacktrace Posten, damit man sehen kann, wo der Fehler auftritt

**Comment by pbd-kn** [comment]
Hmm,
Nein ich habe php 7.4.
Das ist aber sehr komisch. Kann ich Dir noch zusätzliche Info bieten.
Natülich habe ich die Files öffentlich zugänglich gemacht. Unter contao 4.9 lief das auch alles völlig einwandfrei.
Irgendwie ist das Routing dabei umgestellt worden ?? So das keine Route zu

https://mitleben-ev.de/bildergalerien-2022.html
mehr vorhanden ist. Brauchst Du noch zusätzliche Information. 
Den Debug habe ich schon geschickt. Es ist der erste Eintrag, worauf Du noch mehr Info wolltest.

Was meinst Du mit funktioniert bei Dir. Bist Du auf meine Webseite gegangen und hast es probiert??

**Comment by janborg** [comment]
Hi, ich bin nicht der Entwickler, ich setze die Erweiterung aber auch ein und hatte bei Umstellung auf php8 ähnliche Probleme. Unter php7.4 läuft die Erweiterung bei mir aber noch problemlos auch mit Contao 4.13.4. Tut mir leid, mehr kann ich auch nicht sagen.

**Comment by pbd-kn** [comment]
Hi
Ich habe nochmals nachgeforscht.
Unter Einstllungen finde ich keine Tab

Gallery Creator Standard Zugriffsrechte

Laut Doku sollte dort der Albumbesitzer konfiguriert sein. Wie bekomme ich den Tab unter System->Einstellungen

**Comment by pbd-kn** [comment]
Hier meine Anzeige unter Einstellungen
![grafik](https://user-images.githubusercontent.com/75879364/169851548-fde5955f-dcec-4c72-b5b7-90855c050374.png)

**Comment by markocupic** [comment]
@pbd-kn
@janborg

Hallo 

Der Gallery Creator besitzt noch eine Codebasis aus Contao 3 Zeiten. 
Ich werde in der 1er Version keine Bugs mehr fixen, es sei denn es handle sich um einen vergüteten Auftrag. Pull Requests dürfen natürlich gemacht werden.

Es gibt eine Nachfolgeversion, die aber noch im RC-Stadium ist und noch nicht stable ist. 
Auch habe ich vor die HTML5- durch TWIG-Templates zu ersetzen, wenn mal Zeit da ist.
Die alten Templates aus Ver 1.x werden mit der 2er Version auf jeden Fall nicht mehr kompatibel sein. 

Ich danke euch für das Verständnis :-)

Liebe Grüsse 

M.C.

**Comment by pbd-kn** [comment]
Nach Installation von 2.0.0-rc3 tritt der Fehler immer noch auf.

Sie auch 
 
Detailbilder werden nicht angezeigt #24
