### ISSUE TITLE
Detailbilder werden nicht angezeigt

### ISSUE THREAD

**Issue by pbd-kn** [markocupic/gallery-creator-bundle#24]
Hi,
Ich habe nun RCX3 installiert und bekomme imme noch, wenn ich das Album anklicke den Fehler

The Server returned a 404 Error

Ich habe im Gallerieelement die gewünschten Galerien ausgewählt.
![grafik](https://user-images.githubusercontent.com/75879364/183293228-33e21609-88e5-430c-882c-58bf1451a27d.png)

und das Standard Template verwendet

![grafik](https://user-images.githubusercontent.com/75879364/183293267-5d0033dc-5684-49aa-8c72-62ee8e26cb92.png)

Zum einen wird nur eine Galerie angezeigt 
![grafik](https://user-images.githubusercontent.com/75879364/183293323-27afbfaa-6984-4c73-953f-da3efa3433b2.png)

und beim Klick auf die Galerie kommt

![grafik](https://user-images.githubusercontent.com/75879364/183293135-9d2a82a4-9f54-4439-97fd-41711f21f15e.png)

Was mache ich falsch. 
LG
Peter

**Comment by pbd-kn** [comment]
Nochmals nachdem ich den Punkt Album anlegen geht nicht #25 per DB-Änderungen durchgeführt habe.
Funktioniert dies in der neuen Contao-Umgebung.
Es muss also wohl mit dem neuen Routing zusammenhängen.

Für mich gibt es aber nicht die Möglichkeit die gesamte Seite neu aufzusetzen.
Anderseits ist es dringend, da der Kunde mir im Nacken sitzt.
ps. die .htaccess habe ich von der neuen auf die alte Istallation schon übenommen. Keine Änderung.
Klick auf das Album Error: 404

**Comment by markocupic** [comment]
Du kannst auf die 2.0.0-RC5 updaten. Das wird den DB Error beheben. Dein Routing Problem jedoch nicht. Bitte kontaktiere mich dazu per E-Mail.

**Comment by pbd-kn** [comment]
Hi Marko

Ich soll mit Dir Kontakt per Mail aufnehmen, damit wir irgendwie das Routingproblem vom Tisch bekommen.

Das mache ich hiermit. Was soll ich tun.

Ist das überhaupt der richtige E-Mail Kontakt.

Gruß

Peter

 

Von: Marko Cupic 
Gesendet: Montag, 15. August 2022 15:12
An: markocupic/gallery-creator-bundle ***@***.***>
Cc: pbd-kn ***@***.***>; Author ***@***.***>
Betreff: Re: [markocupic/gallery-creator-bundle] Detailbilder werden nicht angezeigt (Issue #24)

 

Du kannst auf die 2.0.0-RC5 updaten. Das wird den DB Error beheben. Dein Routing Problem jedoch nicht. Bitte kontaktiere mich dazu per E-Mail.

**Comment by markocupic** [comment]
Mail-Adress stimmt. Aber bitte nicht über github! Wie lautet deine E-Mail-Adresse?

**Comment by pbd-kn** [comment]
Ok meine Mailadresse ist die obige

***@***.***

 

Von: Marko Cupic 
Gesendet: Montag, 15. August 2022 15:33
An: markocupic/gallery-creator-bundle ***@***.***>
Cc: pbd-kn ***@***.***>; Author ***@***.***>
Betreff: Re: [markocupic/gallery-creator-bundle] Detailbilder werden nicht angezeigt (Issue #24)

 

Mail-Adress stimmt. Aber bitte nicht über github! Wie lautet deine E-Mail-Adresse?

**Comment by pbd-kn** [comment]
pbd at gmx.de
