### ISSUE TITLE
Template ce_gallery_creator nicht mehr vorhanden

### ISSUE THREAD

**Issue by pbd-kn** [markocupic/gallery-creator-bundle#26]
Version 2.0.0.-RC6

Unter Templates wird das ce_gallery_creator nicht mehr angezeigt
![grafik](https://user-images.githubusercontent.com/75879364/186092189-bcfdc6a7-69c6-4162-8f1a-328e7e384656.png)

Im FE-Galleriy Elment wird es zwar angezeigt, aber nicht ausgeführt
Allerdings nur das Standard Template aus meinem Template-Verzeichnis 

ein Template mit dem Namen ce_gallery_creatorPBD.html5 wird nicht zu Auswahl angezeigt
![grafik](https://user-images.githubusercontent.com/75879364/186094073-81fdf546-caf8-47dd-908e-6d934a1f9e87.png)

**Comment by markocupic** [comment]
> Unter Templates wird das ce_gallery_creator nicht mehr angezeigt

Ich glaube, das funktioniert nur mit html5-Templates. Nutze für dein Vorhaben einen Editor und speichere das neue Template updatesicher in `templates/ce_gallery_creator_pbd.html5` oder `contao/templates/ce_gallery_creator_pbd.html5` ab. Aber am besten nimmst du für dein angepasstes Template die originale TWIG Vorlage.

**Comment by pbd-kn** [comment]
Hallo Marko,
das geht natürlich immer.
Ich wollte aber ein twig-Template auswählen.
Bei der Endung html5 wird aber ein normals altes php Template erwartet.
Da sich twig und php aber nicht mischen lassen habe ich ein Problem.

Ich habe meine Templates jetzt auf twig umgestellt und arbeite halt noch mit
ce_gallery_creator.html.twig und den entsprechenden include twigs gallery_greater_.... in meinem template-Verzeichnis.

Ich habe also die Twig-Vorlage aus dem Bundle in mein Template-Verzeichnis übernommen und gehofft, dass ich auch den obersten Namen ändern kann (ce_gallery_creator.html.twig) die Namen für die Include Twigs kann ich problemlos ändern, aber diese werden ja auch explizit aus meinem geänderten in "Root"-twig aufgerufen.

Mach ich da etwas falsch, oder verstehe ich das mit den twig-Templates nicht richtig.
Kann man den Namen des twig nach ce_gallery_creator..html.twig nicht ändern??
Gruß
Peter

**Comment by markocupic** [comment]
Meine angepassten Templates für gallery creator liegen alle im Verzeichnis `contao/templates`

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/1525166/187071368-bc339cbd-81db-4825-8555-448dd0f0ef4f.png">

Hast du das schon ausprobiert?

**Comment by pbd-kn** [comment]
Super, so funktioniert es 
Wird korrekt im Galleriecreater Element angezeigt, und auch aufgerufen.
Ich war immer der Meineung, dass das template Verzeichnis auch in die Suche/Anzeige mit aufgnommen wird.
es sind jetzt alle in contao/templates.

Ich nuss es ja nicht verstehen hauptsache es geht
