### ISSUE TITLE
Contao 4.13.8 - Gallery Creator 2.0-RC6 "missing template"

### ISSUE THREAD

**Issue by Seefahrer** [markocupic/gallery-creator-bundle#27]
Upon updating to RC6 calling any GC-gallery in the FE throws fllwg error:

`request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Could not find template "gallery_creator_album"") in "@Contao_Global/gallery_creator_album_list_view.html5"." at /Users/georg/Sites/stina.luetten-dieks.eu/vendor/twig/twig/src/Template.php line 408 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Could not find template \"gallery_creator_album\"\") in \"@Contao_Global/gallery_creator_album_list_view.html5\". at /Users/georg/Sites/stina.luetten-dieks.eu/vendor/twig/twig/src/Template.php:408)\n[previous exception] [object] (Exception(code: 0): Could not find template \"gallery_creator_album\" at /Users/georg/Sites/stina.luetten-dieks.eu/vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateLoader.php:156)"} **[]`**

The Contao error page is shown, no images ...

**Comment by Seefahrer** [comment]
A downgrade to RC5 may serve as a preliminary workaround ...

**Comment by markocupic** [comment]
Please test the behaviour under gc version 2.0.0-RC7.

**Comment by Seefahrer** [comment]
Hi Marko,

there is unfortunately no improvement in RC7. May be there is some coherence with #26, because if you try to "fork" a template in the templates folder, you may only choose "be_gc_uploader.html5" from markocupic ... other templates are not being offered.

**Comment by markocupic** [comment]
See: https://github.com/markocupic/gallery-creator-bundle/issues/26

**Comment by Seefahrer** [comment]
But that does not solve the a.m. problem. The FE dies with the above mentioned error message because after installation of RC6/RC7 there is no "Contao/templates" folder.

**Comment by markocupic** [comment]
If you are using custom templates, you have to create the folder manually. 

`contao/templates`  lowercase

**Comment by pbd-kn** [comment]
Bei mir hat es geholfen. 
ABER !!!!! nach jeder Änderung Cache löschen sonst geht es nicht

**Comment by Seefahrer** [comment]
Hmmm ... have made folder contao/templates manually and copied all content of vendor/markocupic ... templates also manually to the new folder. Now it works so far, but this cannot be the best update practice if s.o. has customized templates in the old school templates folder.

**Comment by Seefahrer** [comment]
Even without customized templates Contao/templates has not been created. Doing all of the above manually does not fix the problem. The FE collapses with fllwg error:

`[2022-08-29T18:50:21.130701+02:00] request.CRITICAL: Uncaught PHP Exception Error: "Call to a member function getOffset() on null" at /www/htdocs/w00c556f/stina.luetten-dieks.eu/vendor/markocupic/gallery-creator-bundle/src/Controller/ContentElement/AbstractGalleryCreatorController.php line 307 {"exception":"[object] (Error(code: 0): Call to a member function getOffset() on null at /www/htdocs/w00c556f/stina.luetten-dieks.eu/vendor/markocupic/gallery-creator-bundle/src/Controller/ContentElement/AbstractGalleryCreatorController.php:307)"} []
`
