### ISSUE TITLE
Bei Löschen eines Albums werden die Bilder aus Verzeichnis aus dem Verzeichnis gelöscht

### ISSUE THREAD

**Issue by arminfrey** [markocupic/gallery-creator-bundle#31]
Reproduktion:
- Album anlegen
- Bilder aus Verzeichnis wählen, Verzeichnis in der Dateiverwaltung anklicken
- Album danach löschen
- Verzeichnis in der Dateiverwaltung ist gelöscht.

Release 1.2.13

**Comment by markocupic** [comment]
Das ist gewollt so und damals vom Kunden auch explizit so gewünscht.

**Comment by arminfrey** [comment]
Gut, dann kann der Issue geschlossen werden. Für mich dann nicht zu gebrauchen, wenn ich mal ein Album lösche sind meine Bilder weg.
