### ISSUE TITLE
Apparent routing issue with legacy routing mode enabled in Contao 4.13

### ISSUE THREAD

**Issue by ronnybremer** [markocupic/gallery-creator-bundle#32]
I am aware that others had a similar issue but I can't find any clue on how they solved it.

Currently still using version 1 of your plugin, I can perfectly see the gallery overview page including pagination, but I can't get any individual gallery to open. All I get is an error 404, which seems to have to do with routing changes in 4.x of Contao.

With version 2 in active development, would it be advisable to try RC7 with Contao 4.13? Or is there anything I can do to further troubleshoot and fix the routing issue?
In case RC7 is the way to go, I assume it will not only support Contao 5 but also 4, correct?

Thank you,

Ron

**Comment by markocupic** [comment]
@ronnybremer 
Please try version [1.3.0](https://github.com/markocupic/gallery-creator-bundle/tree/1.3.0). The routing issue should have been fixed. If your web server runs on a PHP version < 8.1, you should update Gallery Creator to latest 1.2 version (>=1.2.14)

Keep in mind that version 2.x of the gallery plugin, once it has been published, will surely not support Contao 4.x.

**Comment by ronnybremer** [comment]
Thank you Mark! That solved the issue with the routing. Somehow my Contao Manager was locked into 1.2.
