### ISSUE TITLE
Contao 5.2.4 und Gallery Creator 2.x-dev

### ISSUE THREAD

**Issue by Seefahrer** [markocupic/gallery-creator-bundle#34]
Moin Marko,

ich hoffe Du liest noch mit. Deine Dev-Version läuft prima unter Contao 5.2.4 bis auf eine Kleinigkeit:

Die Großansicht im Detailview erfolgt nicht in einer Lightbox sondern in einem neuen Browserfenster. Glightbox ist installiert.
Leider funktioniert es weder in der GlightBox noch in der Colorbox.

**Comment by markocupic** [comment]
Hallo @Seefahrer 
Kann den Fehler, zumindest was die glightbox angeht, nicht bestätigen. 

Getestet mit Contao 5.2 und gallery-creator-bundle 2.x-dev:
https://4ae-racing-team.ch/bildergalerie/hohjaegiburg-via-roehreni

Werden im Browser (dev mode) irgend welche Skriptfehler angezeigt?

**Comment by Seefahrer** [comment]
Hallo Marko,

nein, es gibt keine Skriptfehler ... Ich habe mal eine Testgalerie angelegt, leider der gleiche Effekt: Keine Lightbox.
Der generierte HTML-Code aus den Devtools sieht aus wie folgt:

`<figure class="image_container">`
   `<a href="/files/gallery_creator_albums/Testordner/ahnentafel_antje.jpg" target="_blank">`
    	`<img src="/assets/images/y/ahnentafel_antje-s4mdr9pp2gwfm74.jpg" alt="" width="350" height="350">`
    `</a>`
`</figure>`

Die "js_glightbox.html5" liegt in /templates.

**Comment by JoT2** [comment]
Moin,
kann das Verhalten bestätigen. 

- Contao 5.2.6
- Php 8.1
- Gallery Creator Bundle 2.x-dev
- inspiredminds/contao-glightbox 1.0.2 
- Contao und Extensions über Contao-Manager installiert

Im Template 

1. j_colorbox deaktiviert
2. js_glightbox aktiviert

Auf einer Seite mit diesem Template eine Galerie (Contao) und eine GalleryCreator-Galerie mit den gleichen Bildern eingerichtet. Ergebnis: Bilder der ContaoGalerie werden in der glightbox geladen, Bilder der GC-Galerie werden in neuem BrowserTab geladen. Keine Fehler in der Konsolenausgabe der DevTools.

**Comment by JoT2** [comment]
Nachtrag: 

- Installation leeres Contao 5.2 mit den GalleryCreator 2.x-dev und contao-glightbox: gLightbox funktioniert nicht, Bild einer kleinen Test-Galerie wird in neuen Tab geladen
- Downgrade auf 5.0: glightbox funktioniert
- Update auf 5.1: glightbox funktioniert
- Update auf 5.2: glightbox funktioniert nicht mehr

**Comment by markocupic** [comment]
@Seefahrer @JoT2 
Ok! Please try the latest build https://github.com/markocupic/gallery-creator-bundle/commit/e6e7fa6f733d957c50fcbbf0d9b3d558501ba806

**Comment by JoT2** [comment]
Sorry :-( Funktioniert auch mit deinem letzten build weder in meiner Testinstallation noch in meinem aktuellen Projekt.

**Comment by markocupic** [comment]
@JoT2 Kann ich mir das mal live ansehen?

**Comment by Seefahrer** [comment]
Moin Marko

siehe: https://www.luetten-dieks.eu/testgalerie

**Comment by markocupic** [comment]
> Moin Marko
> 
> siehe: https://www.luetten-dieks.eu/testgalerie

@Seefahrer Verwendest du dieses [Originaltemplate](https://github.com/markocupic/gallery-creator-bundle/blob/2.x/contao/templates/component/_album_detail_view.html.twig)?

**Comment by Seefahrer** [comment]
Ja, ich verwende das template, welches Du gestern im Build https://github.com/markocupic/gallery-creator-bundle/commit/e6e7fa6f733d957c50fcbbf0d9b3d558501ba806 veröffentlicht hast.

Ich habe Gallery Creator heute Mittag testweise neu installiert, nachdem ich vor Tagen die Galerien auf den Rocksolid Slider umgestellt hatte ...

**Comment by JoT2** [comment]
Beide Installationen laufen lokal in einem Docker-Container...

**Comment by Seefahrer** [comment]
Moin Marko,

vielen Dank, mit Deiner neuen Version funktioniert die Lightbox nun. Eine kleine Unschönheit fiel mir allerdings noch auf:

Bei der Galerieübersicht kommt man nur durch Klicken auf den Titeltext weiter. In der Einzelbildübersicht genügt ein Click auf die Bilder. Es wäre schön, wenn das auch in der Galerieübersicht so wäre.

**Comment by JoT2** [comment]
Yes it works! Danke!

**Comment by Seefahrer** [comment]
Danke Marko, jetzt ist alles bestens  👍

**Comment by Seefahrer** [comment]
Schade ... mit einem weiteren Update soeben hat ein bereits behobener Fehler ein Comeback erlebt:

`request.CRITICAL: Uncaught PHP Exception Error: "Call to a member function getOffset() on null" at AbstractGalleryCreatorController.php line 307 {"exception":"[object] (Error(code: 0): Call to a member function getOffset() on null at /www/htdocs/w00c556f/stina.luetten-dieks.eu/vendor/markocupic/gallery-creator-bundle/src/Controller/ContentElement/AbstractGalleryCreatorController.php:307)"} []
`

**Comment by markocupic** [comment]
Du musst auf den contao5 branch wechseln.

**Comment by Seefahrer** [comment]
Ok, "contao5-dev" requires löst den Knoten ...
