### ISSUE TITLE
Kein Link zum Album in Albumliste

### ISSUE THREAD

**Issue by operatorone** [markocupic/gallery-creator-bundle#4]
In der Albenübersicht weden zwar die Alben angezeigt, jedoch ist die Variable "href" leer, so dass kein Link vorhanden ist und die Detailsansicht des Albums nicht angezeigt werden kann.

Ich verwende das Standardtemplate unter Contao 4.4.20

Hier Screenshots zu meinen Einstellungen:
https://ibb.co/dEmWto
https://ibb.co/npCRR8
https://ibb.co/dCnbR8

**Comment by markocupic** [comment]
Sorry! But I can not reconstruct the error.
