### ISSUE TITLE
Quality thumbnails / photocredits

### ISSUE THREAD

**Issue by astrotiger** [markocupic/gallery-creator-bundle#7]
First of all I want thank you for this great plugin, great job.

I have one point about thumbnails:
The thumbnails quality in the detailed gallery view is worse than that of the standard photo view.
How can I improve the thumbnail quality?

One proposal for the next release:
It is very important to declare the photographer because of copy rights.
So it would be nice, when there would be a textfield , were I can declare the photographer for every album, which I can show at the frontend template. It would be perfect if there would be an extra field, were i can also link to the photographers website.

Many Thanks to you.

**Comment by markocupic** [comment]
@astrotiger 
The thumnails are minified with the standard Contao Image Engine, nothing else.

From version > 1.2.0 there is field "photographer" where you can declare photographers names.
