### ISSUE TITLE
Contao 4.7.5 - Failed to delete Gallery

### ISSUE THREAD

**Issue by Seefahrer** [markocupic/gallery-creator-bundle#8]
Hi Marco,

trying to delete a gallery via GC content element n the Contao backend throws fllwg error:

>Cannot protect folder "files/gallery_creator_albums/erstes_lebensjahr/winterliche_impressionen" because one of its parent folders is public

**Comment by markocupic** [comment]
@Seefahrer 
Ich kann den Fehler nicht reproduzieren. Von wo heraus läschst du die Galerie. 
* Aus dem Gallery-Creator Backend Modul heraus?

Lg Marko

**Comment by Seefahrer** [comment]
@markocupic 
Ja, vom Gallery Creator Plugin unter Inhaltselemente. Wenn ich in der Galerieübersicht auf das Löschsymbol klicke, erhalte ich o.g. Fehlermeldung und die Galerie wird nicht gelöscht.
Fehler besteht auch nach gestrigen Update fort...

**Comment by markocupic** [comment]
Hm...
Kann den Fehler nicht reproduzieren. Getestet auf Contao 4.7.5.
Komisch...
https://drive.google.com/file/d/1YIab7xj9TSWqINX8P8oDDkBeUPlYQT82/view

**Comment by Seefahrer** [comment]
Eine neue Galerie anlegen geht auch nicht ... Fehlermeldung:
```
Forbidden
Was ist das Problem?
Cannot load record "tl_gallery_creator_albums.id=128".```
